name: Publish
on:
  push:
    branches:
      - 'main'

# Publish workflows don't happen at the same time.
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun run publish-ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # TAKE NOTE, you have to generate this in NPM
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # You DON'T need to generate this, it's automatic by GitHub Workflows.
